config/routes.rb
Peekbox::Application.routes.draw do
  resources :s3_uploads

	devise_for :users, :controllers => {:session => "user/session"} 

	post "zencoder-callback" => "zencoder_callback#create", :as => "zencoder_callback"

	get "profile" => "profile/profile#index"

  get "home" => "home#test_slider"


	namespace :admin do
		resources :categories, :only => [:index, :new, :create, :edit, :update] 
		resources :albums
		resources :contests do
			member do
				get "change_status"
			end
		end
		resources :eligibilities
		resources :feature, :only => [:index] do
			collection do
				get "events"
				get "special"
				get "videos"
				get "albums"
			end
		end
		resources :video_ads
		resources :ads
		resources :event_banner
		resources :banner
		resources :user do
			collection do
				get "ban"
				get "unban"
				get "ban_list"
				get "delete_user"
				get "make_admin"
				get "make_normal"
				get "admin"
			end
		end
	end

	#Users
	namespace :profile do
		resources :video_bookmark do
			collection do
				post "unbookmark"
			end
		end
		resources :picture_bookmark do
			collection do
				post "unbookmark"
			end
		end
		resources :bookmark, :only => [:index, :create, :destroy] do
			collection do
				post "unbookmark"
			end
		end
		resources :information
		resources :crop
		resources :user, :only => [:save, :update] do 
			resources :wall_post, :only => [:create, :destroy]
			collection do
				post "save"
			end
		end
		resources :users, :only => [:index] do 
			collection do
				post "search"
			end
		end
		resources :albums do
			resources :pictures do 
				collection do
					post 'multiupload'
				end
			end
		end
		resources :friends do
			collection do
				get 'search'
				get 'all'
				get 'add', :path => 'add/:id'
			end
		end
		resources :messages do
			collection do
				get "inbox"
				post "send_message"
				get "sent"
        get "trash"
				get "compose"
				post "move_to_label", :path => 'move_to_label/:id'
        get "autocomplete_user_username"
        post "delete_checked", :put

			end
		end
		resources :events
		resources :videos do
			collection do
				get "uploaded"
			end
			resources :comments
		end
	end

	#Videos
	resources :videos, :only => [:show, :index]

	# Events
	resources :events, :only => [:show, :index] do
    collection do
      get "show_to", :path => 'show_to/:id'
    end
  end

	#Albums
	resources :albums, :only => [:show, :index] do
		resources :pictures, :only => [:show, :index]
	end

	resources :category, :only => [:show], :path => "/video/category/"



	get "help" => "static#help"

	get "company" => "static#company"
	post "contact" => "static#contact"

  root :to => 'home#index'
  match ":username" => "information#show", :as => "other_user"
  match ":username/friends" => "information#friends", :as => "other_user_friends"

end

app/controllers/profile/albums_controller.rb
class Profile::AlbumsController < Profile::ProfileController 

  def index
		@albums = current_user.albums.page(params[:page])
  end

	def create
		@album = Album.new
		@album.title = params[:album][:title]
		@album.description = params[:album][:description]
		@album.image = params[:album][:image]
		@album.user = current_user
		if @album.save
			redirect_to profile_album_pictures_path(@album), :notice => "Successfully added an Album!"
		else
			render :action => "new"
		end
	end

  def new
		@album = Album.new
  end

	def update
		@album = Album.find_by_id(params[:id])
		@album.title = params[:album][:title]
		@album.description = params[:album][:description]
		@album.image = params[:album][:image]
		@album.featured = params[:album][:featured]
		if @album.save
			redirect_to profile_album_pictures_path(@album), :notice => "Successfully updated an Album!"	
		else
			render :action => "edit", :alert => "Error on updating an Album"
		end
	end

	def edit
		unless current_user.admin
			@album = current_user.albums.find_by_id(params[:id])
		else
			@album = Album.find_by_id(params[:id])
		end
	end

	def destroy
		@album = Album.find_by_id(params[:id])
		if current_user == @album.user
			if @album.destroy
				redirect_to profile_albums_path, :notice => "Successfully deleted an Album!"	
			else
				redirect_to profile_albums_path, :alert => "Error on deleting an Video!"	
			end
		end

	end
end

app/controllers/profile/bookmark_controller.rb
class Profile::BookmarkController < Profile::ProfileController
  def index
		@user_events = current_user.peekme
  end

  def create
		@bookmark = Bookmark.new
		@bookmark.user = current_user
		@bookmark.peekme = Event.find(params[:event])
		if @bookmark.save!
			redirect_to event_path(@bookmark.peekme), :notice => "Successfully added a bookmark"
		else
			redirect_to events_path, :alert => "Error adding a bookmark"
		end
  end

  def destroy
		@bookmarked = Bookmark.where(:user_id => current_user.id, :event_id => params[:id]).first
		if @bookmarked.destroy
			redirect_to profile_bookmark_index_path, :notice => "Successfully removed a bookmark"
		else
			redirect_to events_path, :alert => "Error removing a bookmark"
		end
  end

	def unbookmark
		@bookmarked = Bookmark.where(:user_id => current_user.id, :event_id => params[:id]).first
		if @bookmarked.destroy
			redirect_to event_path(@bookmarked.peekme), :notice => "Successfully removed a bookmark"
		else
			redirect_to events_path, :alert => "Error removing a bookmark"
		end

	end

end

app/controllers/profile/comments_controller.rb
class Profile::CommentsController < Profile::ProfileController
	def create
		@video = Video.find(params[:video_id])
		@comment = Comment.new
		@comment.body = params[:comment][:text]
		@comment.video = @video
		@comment.user = current_user

		if @comment.save
			redirect_to video_path(@video), :notice => "Successfully added a comment!"	
		else
			redirect_to video_path(@video), :alert => "Failed add a comment!"	
		end

	end

  def new
  end

  def index
  end

  def show
  end

  def destroy
  end

end

app/controllers/profile/crop_controller.rb
class Profile::CropController < Profile::ProfileController
  def edit
		@user = User.find_by_id(params[:id])
		if @user.profilepic == nil
			redirect_to edit_profile_information_path(@user.id), :notice => "Please upload a photo!"
		end
  end

  def update
		@user = User.find_by_id(params[:user][:id])
		if params[:cx].to_i > 1
			@user.crop_x = params[:cx]
			@user.crop_y = params[:cy]
			@user.crop_h = params[:h]
			@user.crop_w = params[:w]
		end
		if @user.save! 
			redirect_to profile_path, :notice => "Successfully save crop photo!"
		else
			render :action => "index"
		end
  end

end

app/controllers/profile/events_controller.rb
class Profile::EventsController < Profile::ProfileController

	def index
		@user_events = current_user.events
	end

	def new
		@event = Event.new
	end

	def create
		@event = Event.new(params[:event])
		@event.user = current_user
		if @event.save
			redirect_to @event, :notice => "Successfully added an Event!"	
		else
			render :action => "new"
		end
	end

	def update
		@event = Event.find_by_id(params[:event][:id])
		@event.title = params[:event][:title]
		@event.description = params[:event][:description]
		@event.date = params[:event][:date]
		@event.location = params[:event][:location]
		@event.image = params[:event][:image]
		@event.featured = params[:event][:featured]
		@event.special = params[:event][:special]
		if @event.save!
			redirect_to @event, :notice => "Successfully updated an Event!"	
		else
			render :action => "new"
		end
	end

	def edit
		unless current_user.admin
			@event = current_user.events.find_by_id(params[:id])
		else
			@event = Event.find_by_id(params[:id])
		end
	end

	def destroy
		@event = Event.find_by_id(params[:id])
		if current_user == @event.user
			if @event.destroy
				redirect_to profile_events_path, :notice => "Successfully deleted an Event!"	
			else
				redirect_to profile_events_path, :alert => "Error on deleting an Event!"	
			end
		end

	end

end

app/controllers/profile/friends_controller.rb
class Profile::FriendsController < Profile::ProfileController
  def index
		@friends = current_user.friends.order("id").page(params[:page])
  end

	def all
		@friends = User.order("id").where("id != ?", "#{current_user.id}").page(params[:page])
	end

	def add
		@user = current_user
		@friend = User.find(params[:id])
		if @user.is_stranger(@friend)
			@friend.friends << @user
			@user.friends << @friend
			redirect_to profile_friends_path, :notice => "Successfully added #{@friend.username} as a friend!"
		else
			redirect_to profile_friends_path, :error => "unable to add this friend"
		end
	end

	def search
		@friends = Friends.search_username(params[:friend][:username])
	end

  def show
  end

  def new
  end

  def edit
  end

  def destroy
		@friendship = Friendship.where(:friend_id => params[:id], :user_id => current_user.id)
		@friendship2 = Friendship.where(:user_id => params[:id], :friend_id => current_user.id)
		@friend = User.find(params[:id])
		if @friendship.destroy_all and @friendship2.destroy_all
			redirect_to profile_friends_path, :notice => "Successfully unfriend #{@friend.username}!"
		else
			redirect_to profile_friends_path, :error => "unable to unfriend this friend"
		end
  end

  def update
  end

  def create
  end

end

app/controllers/profile/information_controller.rb
class Profile::InformationController < Profile::ProfileController
  def search
  end

  def show
  end

	def edit
		@user = User.find(params[:id])
	end

	def save
		@user = User.find(params[:id])
	end

end

app/controllers/profile/messages_controller.rb
class Profile::MessagesController < Profile::ProfileController

  autocomplete :user, :username

  before_filter :load_user_message, :only => :destroy


  def inbox
		@messages = current_user.received_messages.page(params[:page]).per(20)
  end

  def show
  end

  def destroy
    raise Exception if @user_message.user != current_user
    @user_message.destroy
    redirect_to request.referer, :notice => "Delete Success!"
  end

  def delete_checked
    message_ids = params[:user_message_ids]
    message_ids.each do |user_message|
      message = UserMessage.find(user_message)
      message.update_attribute(:status, 'deleted')
      message.update_attribute(:deleted_at, Time.now)
    end

    flash[:notice] = 'Successfully deleted!'
    redirect_to request.referer
  end

  def move_to_label
    user_message = UserMessage.find(params[:id])
    user_message.update_attributes(:label => params[:label])
    redirect_to request.referer, :notice => "Successfully Updated!"
  end

  def send_message
    begin
      form_params = params[:message]
      form_params[:recipients] = [params[:message][:friend_id]] #TODO: change this after implementing multiple recipients
      form_params.delete(:friend_id)
      current_user.messages.create!(form_params)
      redirect_to sent_profile_messages_path, :notice => "Message Sent!"
    rescue ActiveRecord::RecordInvalid => e
      redirect_to compose_profile_messages_path, :alert => e.message
    end
  end

  def sent
		@messages = current_user.sent_messages.page(params[:page]).per(20)
  end

  def trash
    @messages_tinbox = current_user.trash_messages_tinbox.page(params[:page]).per(20)
    @messages_tsent = current_user.trash_messages_tsent.page(params[:page]).per(20)
  end

  def compose
		@friends = current_user.friends
    redirect_to profile_path, :alert => "You currently have no friends. Please add some friends to use this feature." if @friends.empty?
  end

  def get_autocomplete_items(parameters)
    items = super(parameters)
    items= items.where("users.id IN(?)", current_user.friends)
  end

  private

  def load_user_message
    @user_message = UserMessage.find(params[:id])
  end


end

app/controllers/profile/picture_bookmark_controller.rb
class Profile::PictureBookmarkController < Profile::ProfileController
  def index
		@marked= current_user.picture_marked
  end

  def new
  end

	def unbookmark
		@bookmarked = PictureBookmark.where(:user_id => current_user.id, :picture_id => params[:id]).first
		if @bookmarked.destroy
			redirect_to album_picture_path(@bookmarked.picture_marked.album, @bookmarked.picture_marked), :notice => "Successfully removed a bookmark"
		else
			redirect_to pictures_path, :alert => "Error removing a bookmark"
		end

	end

  def create
		@bookmark = PictureBookmark.new
		@bookmark.user = current_user
		@bookmark.picture_marked = Picture.find(params[:picture])
		if @bookmark.save!
			redirect_to album_picture_path(@bookmark.picture_marked.album, @bookmark.picture_marked), :notice => "Successfully added a bookmark"
		else
			redirect_to pictures_path, :notice => "Error adding a picture bookmark"
		end
  end

  def destroy
		@bookmarked = PictureBookmark.where(:user_id => current_user.id, :picture_id => params[:id]).first
		if @bookmarked.destroy
			redirect_to album_picture_path(@bookmark.picture_marked.album, @bookmark.picture_marked), :notice => "Successfully removed a bookmark"
		else
			redirect_to pictures_path, :alert => "Error removing a bookmark"
		end
  end

  def update
  end

  def edit
  end

end

app/controllers/profile/pictures_controller.rb
class Profile::PicturesController < Profile::ProfileController

  def index
			@album = current_user.albums.find(params[:album_id])
			@pictures = @album.pictures
  end

  def edit
		if current_user.admin
			@album = Album.find(params[:album_id])
		else
			@album = current_user.albums.find(params[:album_id])
		end
		@picture = Picture.find(params[:id])
  end

	def multiupload
		@album = Album.find_by_id(params[:album_id])
		if !@album.nil?
			@picture = Picture.new(params[:picture])
			@picture.user = current_user
			@picture.album = @album
			if @picture.save!
				render :nothing => true
			else
				render :nothing => true
			end
		else
			render :action => "index"
		end
	end

  def show
  end

  def create
		@album = Album.find_by_id(params[:album_id])
		if !@album.nil?
			@picture = Picture.new(params[:picture])
			@picture.user = current_user
			@picture.album = @album
			if @picture.save!
				redirect_to profile_album_pictures_path(@album), :notice => "Successfully added a Photo!"
			else
				render :action => "index"
			end
		else
			render :action => "index"
		end
  end

  def update
		@album = Album.find_by_id(params[:album_id])
		if !@album.nil?
			@picture = Picture.find(params[:id])
			@picture.user = current_user
			@picture.album = @album
			@picture.description = params[:picture][:description]
			@picture.title = params[:picture][:title]
			if @picture.save!
				redirect_to profile_album_pictures_path(@picture.album), :notice => "Successfully deleted an Picture!"	
			else
				redirect_to profile_album_pictures_path(@picture.album), :alert => "Error on deleting an Picture!"	
			end
		else
				redirect_to profile_album_pictures_path(@picture.album), :alert => "Error on fetching an album!"	
		end
  end

  def destroy
		@picture = Picture.find(params[:id])
		if current_user == @picture.user || current_user.admin
			if @picture.destroy
				redirect_to album_pictures_path(@picture.album), :notice => "Successfully deleted an Picture!"	
			else
				redirect_to profile_album_pictures_path(@picture.album), :alert => "Error on deleting an Picture!"	
			end
		end
  end

end

app/controllers/profile/profile_controller.rb
class Profile::ProfileController < ApplicationController
	before_filter :authenticate_user!
	before_filter :banned_user!

	def index
		@user = current_user
	end

	def banned_user!
		if current_user.banned == true
			redirect_to destroy_user_session_path, :method => :delete
		end
	end

end

app/controllers/profile/search_controller.rb
class Profile::SearchController < ApplicationController
  def index
  end

  def user
  end

  def result
  end

end

app/controllers/profile/user_controller.rb
class Profile::UserController < Profile::ProfileController

	def index
		@user = current_user
	end
	def result
	end

	def search
	end

	def edit
	end

	def update
		@user = User.find_by_id(params[:user][:id])
		@user.shoutout = params[:user][:shoutout]
		@user.first_name = params[:user][:first_name]
		@user.last_name= params[:user][:last_name]
		@user.location = params[:user][:location]
		@user.occupation = params[:user][:occupation]
		@user.sex = params[:user][:sex]
		@user.website = params[:user][:website]
		@user.profilepic = params[:user][:profilepic]

		if @user.save! 
			redirect_to edit_profile_crop_path(@user), :notice => "Successfully save profile information!"
		else
			render :action => "index"
		end
	end
end

app/controllers/profile/users_controller.rb
class Profile::UsersController < Profile::ProfileController
  def index
  end

  def search
		username = params[:friend][:username]
		@users = User.where("username LIKE ?", "%#{username}%")	
  end

end

app/controllers/profile/wall_post_controller.rb
class Profile::WallPostController < Profile::ProfileController
  def create
		@wall_post = WallPost.new
		@wall_post.poster = current_user
		@user = User.find(params[:user_id])
		@wall_post.user = @user
		@wall_post.post = params[:wall_post][:post]
		if @wall_post.save!
			redirect_to other_user_path(@user.username), :notice => "Sucessfully added a Wall Post!"
		else
			redirect_to other_user_path(@user.username), :notice => "Error on adding a Wall Post!"
		end
  end

  def destroy
  end

end

app/helpers/profile/albums_helper.rb
module Profile::AlbumsHelper
end

app/helpers/profile/bookmark_helper.rb
module Profile::BookmarkHelper
end

app/helpers/profile/comments_helper.rb
module Profile::CommentsHelper
end

app/views/layouts/profile/_administrator_menu.html.haml
-if current_user.admin?
	%div#page-info{:style => "height:60px;margin-top:20px"}
		%h2
			Peekbox Admin Dashboard
	%div#dashboard{:style => "margin-top:20px"}
		%div.link
			Featured
			%ul.link
				%li.item
					= link_to 'Featured Event List' , events_admin_feature_index_path
				%li.item
					= link_to 'Special Event List', special_admin_feature_index_path 
				%li.item
					= link_to 'Featured Video List' , videos_admin_feature_index_path
				%li.item
					= link_to 'Featured Album List' , albums_admin_feature_index_path
		%div.link
			Sponsored Ads
			%ul.link
				%li.item
					= link_to 'Skyscraper Ads' , admin_ads_path
				%li.item
					= link_to 'Add Skyscraper Ads' , new_admin_ad_path
				%li.item
					= link_to 'PreRoll Video' , admin_video_ads_path
				%li.item
					= link_to 'Add PreRoll Video' , new_admin_video_ad_path
		%div.link
			Banners
			%ul.link
				%li.item
					= link_to 'Home Banner' , admin_banner_index_path
				%li.item
					= link_to 'Add Home Banner' , new_admin_banner_path
				%li.item
					= link_to 'Event Banner' , admin_event_banner_index_path
				%li.item
					= link_to 'Add Event Banner' , new_admin_event_banner_path
		%div.link
			User Management
			%ul.link
				%li.item
					= link_to 'Banned User List' , ban_list_admin_user_index_path
				%li.item
					= link_to 'Ban a User' , admin_user_index_path
				%li.item
					= link_to 'Admin User' , admin_admin_user_index_path
		%div.link
			Campaigns
			%ul.link
				%li.item
					= link_to 'Category' , admin_categories_path
				%li.item
					= link_to 'Add Contest' , new_admin_contest_path
				%li.item
					= link_to 'View Submitted Videos' , admin_contests_path
				%li.item
					= link_to 'Eligibility Code List' , admin_eligibilities_path
				%li.item
					= link_to 'Import Eligibility Code' , new_admin_eligibility_path
		%br{:style=>"clear:both"}

app/views/layouts/profile/_profile_menu.html.haml
%div#dashboard
    %div#avatar
        -if current_user.profilepic == nil
            %h3
                Avatar Image:
            %div
                =image_tag current_user.profilepic_url(:profile_pic).to_s, :id => "onprofilePicture"

    %div.link
        Videos
        %ul.link
            %li.item
                = link_to 'My peek' , profile_video_bookmark_index_path
            %li.item
                = link_to 'View Videos' , profile_videos_path
            %li.item
                = link_to 'Add Video' , new_profile_video_path
    %div.link
        Photos
        %ul.link
            %li.item
                = link_to 'My peek' , profile_picture_bookmark_index_path
            %li.item
                = link_to 'View Albums' , profile_albums_path
            %li.item
                = link_to 'Add Album' , new_profile_album_path
    %div.link
        Events
        %ul.link
            %li.item
                = link_to 'My peek' , profile_bookmark_index_path
            %li.item
                = link_to 'View Events' , profile_events_path
            %li.item
                = link_to 'Add Event' , new_profile_event_path
    %div.link
        Messages
        %ul.link
            -unless current_user.friends.count == 0
                %li.item
                    = link_to 'Compose' ,compose_profile_messages_path
            %li.item
                = link_to 'Inbox', inbox_profile_messages_path
            %li.item
                = link_to 'Sent', sent_profile_messages_path
            %li.item
                = link_to 'Trash', trash_profile_messages_path

    %div.link
        Friends
        %ul.link
            %li.item
                = link_to 'Friends', profile_friends_path
            %li.item
                = link_to 'Search Friend', all_profile_friends_path
    %div.link
        Profile
        %ul.link
            %li.item
                = link_to 'Profile Page', other_user_path(current_user.username)
            %li.item
                = link_to 'Change Information', edit_profile_information_path(current_user)
            %li.item
                = link_to 'Crop Profile Picture', edit_profile_crop_path(current_user.id)

    %br{:style=>"clear:both"}
%br{:style=>"clear:both"}

app/views/layouts/profile/profile.html.haml
!!! 5
%head
	%title 
		Peekbox
	= stylesheet_link_tag "application"
	= javascript_include_tag "application"
	= csrf_meta_tags
	= favicon_link_tag "pb/favicon.jpg"
%body
	= render :partial => "layouts/header"
	%div#wrapper
		#container_wide
			#container
				%br{:style => "clear:both"}
				%div#page-info
					%h2
						Welcome 
						=link_to current_user.username, other_user_path(current_user.username)
					%h2
						Peekbox User Dashboard 
				%br{:style => "clear:both"}
				=render "layouts/profile/profile_menu"
				-unless current_user.admin == false
					=render "layouts/profile/administrator_menu"
				%div#dashboard
				%div#flash
					%span.notice
						= notice
					%span.alert
						= alert
				%br{:style => "clear:both"}
				= yield
				%br{:style => "clear:both"}
		= render :partial => "layouts/twitter"
		= render :partial => "layouts/footer"
		%script{:type => "text/javascript"}
			$(function() {
			$('#tweets').tweets({username:'peekbox', cycle:true});
			});
		= yield :scripts
		= render :partial => "layouts/bottom"