config/routes.rb
Peekbox::Application.routes.draw do
  resources :s3_uploads

	devise_for :users, :controllers => {:session => "user/session"} 

	post "zencoder-callback" => "zencoder_callback#create", :as => "zencoder_callback"

	get "profile" => "profile/profile#index"

  get "home" => "home#test_slider"


	namespace :admin do
		resources :categories, :only => [:index, :new, :create, :edit, :update] 
		resources :albums
		resources :contests do
			member do
				get "change_status"
			end
		end
		resources :eligibilities
		resources :feature, :only => [:index] do
			collection do
				get "events"
				get "special"
				get "videos"
				get "albums"
			end
		end
		resources :video_ads
		resources :ads
		resources :event_banner
		resources :banner
		resources :user do
			collection do
				get "ban"
				get "unban"
				get "ban_list"
				get "delete_user"
				get "make_admin"
				get "make_normal"
				get "admin"
			end
		end
	end

	#Users
	namespace :profile do
		resources :video_bookmark do
			collection do
				post "unbookmark"
			end
		end
		resources :picture_bookmark do
			collection do
				post "unbookmark"
			end
		end
		resources :bookmark, :only => [:index, :create, :destroy] do
			collection do
				post "unbookmark"
			end
		end
		resources :information
		resources :crop
		resources :user, :only => [:save, :update] do 
			resources :wall_post, :only => [:create, :destroy]
			collection do
				post "save"
			end
		end
		resources :users, :only => [:index] do 
			collection do
				post "search"
			end
		end
		resources :albums do
			resources :pictures do 
				collection do
					post 'multiupload'
				end
			end
		end
		resources :friends do
			collection do
				get 'search'
				get 'all'
				get 'add', :path => 'add/:id'
			end
		end
		resources :messages do
			collection do
				get "inbox"
				post "send_message"
				get "sent"
        get "trash"
				get "compose"
				post "move_to_label", :path => 'move_to_label/:id'
        get "autocomplete_user_username"
        post "delete_checked", :put

			end
		end
		resources :events
		resources :videos do
			collection do
				get "uploaded"
			end
			resources :comments
		end
	end

	#Videos
	resources :videos, :only => [:show, :index]

	# Events
	resources :events, :only => [:show, :index] do
    collection do
      get "show_to", :path => 'show_to/:id'
    end
  end

	#Albums
	resources :albums, :only => [:show, :index] do
		resources :pictures, :only => [:show, :index]
	end

	resources :category, :only => [:show], :path => "/video/category/"



	get "help" => "static#help"

	get "company" => "static#company"
	post "contact" => "static#contact"

  root :to => 'home#index'
  match ":username" => "information#show", :as => "other_user"
  match ":username/friends" => "information#friends", :as => "other_user_friends"

end

app/controllers/information_controller.rb
class InformationController < ApplicationController

	def index
	end	

  def search
  end

  def show
		@user = User.find_by_username(params[:username])
		@wall_posts = @user.wall_post
		@videos = @user.videos.for_page
		@albums = @user.albums.for_page
		@events = @user.events.for_page
		@ad ||= Ads.find_by_location("user")
  end

	def friends
		@user = User.find_by_username(params[:username])
		@friends = @user.friends.page(params[:page])
	end

end

app/controllers/profile/information_controller.rb
class Profile::InformationController < Profile::ProfileController
  def search
  end

  def show
  end

	def edit
		@user = User.find(params[:id])
	end

	def save
		@user = User.find(params[:id])
	end

end

app/helpers/information_helper.rb
module InformationHelper
end

app/helpers/profile/information_helper.rb
module Profile::InformationHelper
end

app/views/information/_controls.html.haml
%br{:style=>"clear:both"}
-unless current_user == nil
	%div#control-panel
		- unless current_user == @user
			%div{:style=>"float:left"}
				-if current_user.is_stranger(@user)
					=link_to "Add Friend", add_profile_friends_path(@user)
				-else
					=link_to "UnFriend", profile_friend_path(@user), :method => :delete
					%div
						=link_to "Send Message", compose_profile_messages_path
			%div
				&nbsp;
				=link_to "View Friends", other_user_friends_path(@user.username)
		- else
			%div
				=link_to "View Friends", other_user_friends_path(@user.username)

app/views/information/_data.html.haml
%div#information
	%div#shoutout.info
		%b
			Shoutout: &nbsp;
		=@user.shoutout
	%br
	%div#name.info
		%b
			=@user.first_name
			=@user.last_name
	%div#sex.info
		%b
			Sex:&nbsp;
		=@user.sex
	%div#location.info
		%b
			location:&nbsp;
		=@user.location
	%div#date-joined.info
		%b
			Date joined:&nbsp;
		=@user.created_at
	%br
	%div#pb-site.info
		%b
			Peekbox site: &nbsp;
		= auto_link("http://#{request.host+request.fullpath}")
	%div#website.info
		%b
			website:&nbsp;
		=auto_link(@user.website)

app/views/information/_items.html.haml
%br{:style=>"clear:both"}
%div#videos_list
	-unless @videos.empty?
		%h3
			VIDEOS
		-@videos.each do |vid|
			%div#video_each
				%p#thumb
					%div.thumbnail-wrapper
						=link_to (image_tag vid.thumbnails.first.url, :class => "thumbnails" ,:alt => "#{vid.category.title.to_s}_#{vid.title.to_s}"), video_path(vid.id)
						%div.item-title-wrapper
							%p.item-title
								=vid.title
		%br{:style=>"clear:both"}
		%div.view-all-link
			%p
				=link_to "View All", videos_path
%br{:style=>"clear:both"}
%div#albums_list
	-unless @albums.empty?
		%h3
			ALBUMS
		%div#album_each
			-@albums.each do |album|
				%div#each
					%div#album_cover.thumbnail-wrapper
						=link_to (image_tag album.image_url(:album_thumb).to_s), album_pictures_path(album) 
						%div#album_title.item-title-wrapper
							%p.item-title
								=album.title	
		%br{:style=>"clear:both"}
		%div.view-all-link
			%p
				=link_to "View All", albums_path 
%br{:style=>"clear:both"}
%div#events_list
	-unless @events.empty?
		%h3
			EVENTS
		%div#each
			-@events.each do |event|
				%div#each
					%div#event_thumb.thumbnail-wrapper
						=link_to (image_tag event.image_url(:thumb).to_s), event_path(event) 
						%div#event_title.item-title-wrapper
							%p.item-title
								=event.title	
		%br{:style=>"clear:both"}
		%div.view-all-link
			%p
				=link_to "View All", events_path
%br{:style=>"clear:both"}

app/views/information/_pic.html.haml
%div#pic
	%div#profile_pic
		-if @user.profilepic?
			= image_tag @user.profilepic_url(:profile_pic)
		-else
			= image_tag "no-profile-pic.jpg" , :style => "height:331px;width:250px;"

app/views/information/_wall_post.html.haml
%br{:style=>"clear:both"}
%h3
	Wall Post
%div#wall
	%div.post
		-@wall_posts.each do |post|
			%div
				-unless post.poster == nil
					-unless post.poster.profilepic == nil
						%div#wall-post
							%div#wall-poster-pic
								=link_to (image_tag post.poster.profilepic_url(:profile_pic) ,:style => "width:50px;height:76px"), other_user_path(post.poster.username)
							%div#wall-post-body
								%p
									%span#bold
										=link_to post.poster.username, other_user_path(post.poster.username)
									says:
								%p.time-ago
									=distance_of_time_in_words_to_now(post.created_at)
								%br
								%p
									=post.post
							%br{:style => "clear:both"}

%h3
	Leave a Reply
%br{:style => "clear:both"}
=form_for :wall_post, :url => profile_user_wall_post_index_path(@user), :method => :post do |wall_post|
	=wall_post.text_area :post
	%br
	=submit_tag "Post to wall", :id => "submit"

app/views/information/friends.html.haml
%div#page-info
	%span#title
		Friends of 
		=@user.username
	%span#desc
		&nbsp;
%br{:style => "clear:both;"}
%div
	=paginate @friends
%div#friend_list
	-@friends.each do |friend|
		%div#each
			%p#thumb
				%div.thumbnail-wrapper
					-if friend.profilepic?
						=link_to (image_tag friend.profilepic_url(:profile_pic_thumb), :class => "thumbnails" ,:alt => "#{friend.username.to_s}_#{friend.username.to_s}"), other_user_path(friend.username)
					- else
						= link_to (image_tag "no-profile-pic.jpg", :style => "height:114px;width:200px;"), other_user_path(friend.username)
					%div.item-title-wrapper
						%p.item-title
							=friend.username

%br{:style=>"clear:both"}

app/views/information/search.html.haml
%h1 Information#search
%p Find me in app/views/information/search.html.haml

app/views/information/show.html.haml
-if @user.banned
	%h1
		BANNED USER
	%br{:style => "clear:both"}
=render "pic"
=render "data"
- unless @ad == nil
	%div.ads
		=link_to (image_tag @ad.banner_url(:banner_ad)), @ad.url
=render "controls"
%br{:style => "clear:both"}
%div#user-page-content
	%div#user-page-control
		%a{:id => "media-btn", :class => "userpage-btn user-page-selected"}
			Media
		%a{:id => "wall-btn", :class => "userpage-btn"}
			Wall
	%div#user-page-data
		%div#user-page-wall-post
			=render "wall_post"
		%div#user-page-media
			=render "items"