config/routes.rb
Peekbox::Application.routes.draw do
  resources :s3_uploads

	devise_for :users, :controllers => {:session => "user/session"} 

	post "zencoder-callback" => "zencoder_callback#create", :as => "zencoder_callback"

	get "profile" => "profile/profile#index"

  get "home" => "home#test_slider"


	namespace :admin do
		resources :categories, :only => [:index, :new, :create, :edit, :update] 
		resources :albums
		resources :contests do
			member do
				get "change_status"
			end
		end
		resources :eligibilities
		resources :feature, :only => [:index] do
			collection do
				get "events"
				get "special"
				get "videos"
				get "albums"
			end
		end
		resources :video_ads
		resources :ads
		resources :event_banner
		resources :banner
		resources :user do
			collection do
				get "ban"
				get "unban"
				get "ban_list"
				get "delete_user"
				get "make_admin"
				get "make_normal"
				get "admin"
			end
		end
	end

	#Users
	namespace :profile do
		resources :video_bookmark do
			collection do
				post "unbookmark"
			end
		end
		resources :picture_bookmark do
			collection do
				post "unbookmark"
			end
		end
		resources :bookmark, :only => [:index, :create, :destroy] do
			collection do
				post "unbookmark"
			end
		end
		resources :information
		resources :crop
		resources :user, :only => [:save, :update] do 
			resources :wall_post, :only => [:create, :destroy]
			collection do
				post "save"
			end
		end
		resources :users, :only => [:index] do 
			collection do
				post "search"
			end
		end
		resources :albums do
			resources :pictures do 
				collection do
					post 'multiupload'
				end
			end
		end
		resources :friends do
			collection do
				get 'search'
				get 'all'
				get 'add', :path => 'add/:id'
			end
		end
		resources :messages do
			collection do
				get "inbox"
				post "send_message"
				get "sent"
        get "trash"
				get "compose"
				post "move_to_label", :path => 'move_to_label/:id'
        get "autocomplete_user_username"
        post "delete_checked", :put

			end
		end
		resources :events
		resources :videos do
			collection do
				get "uploaded"
			end
			resources :comments
		end
	end

	#Videos
	resources :videos, :only => [:show, :index]

	# Events
	resources :events, :only => [:show, :index] do
    collection do
      get "show_to", :path => 'show_to/:id'
    end
  end

	#Albums
	resources :albums, :only => [:show, :index] do
		resources :pictures, :only => [:show, :index]
	end

	resources :category, :only => [:show], :path => "/video/category/"



	get "help" => "static#help"

	get "company" => "static#company"
	post "contact" => "static#contact"

  root :to => 'home#index'
  match ":username" => "information#show", :as => "other_user"
  match ":username/friends" => "information#friends", :as => "other_user_friends"

end

app/models/video.rb
class Video < ActiveRecord::Base
	belongs_to :user
	belongs_to :category
	belongs_to :contest
	has_one :eligibility_code
	has_many :comments
	has_many :thumbnails
  has_many :video_bookmarks
	mount_uploader :media, MediaUploader
	attr_accessible :media
	paginates_per 21

	validates_presence_of :category
	validates_presence_of :user
	validates_presence_of :media

	scope :processed, where(:processed => true)
	scope :featured, processed.where(:featured => true)
	scope :for_page, order(:created_at).limit(3).reverse_order

	def processed!
		update_attribute(:processed, true)
	end
	
end

app/controllers/profile/videos_controller.rb
class Profile::VideosController < Profile::ProfileController

	def index
		@videos = current_user.videos.processed.order("id").page(params[:page])
		@all_categories = Category.all
	end

	def new
		@contests = Contest.enabled
		@all_category = Category.all
		@video = Video.new
	end

	def edit
		@all_category = Category.all
		@video = Video.find_by_id(params[:id])
	end

	def destroy
		@video = Video.find_by_id(params[:id])
		if current_user == @video.user
			if @video.destroy
				redirect_to profile_videos_path, :notice => "Successfully deleted a Video!"	
			else
				redirect_to profile_videos_path, :alert => "Error on deleting an Video!"	
			end
		end

	end

	def update 
		@video = Video.find_by_id(params[:video][:id])
		@video.title = params[:video][:title]
		@video.description = params[:video][:description]
		@video.category = Category.find_by_id(params[:video][:category_id])
		@video.featured = params[:video][:featured]
		if @video.save! 
			redirect_to profile_videos_path, :notice => "Successfully updated a video!"
		else
			render :action => "edit"
		end
	end

	def create
		@video = Video.new
		@video.title = params[:video][:title]
		@video.description = params[:video][:description]
		@video.category = Category.find_by_id(params[:video][:category_id])
		unless params[:video][:contest_id] == ""
			@video.contest = Contest.find(params[:video][:contest_id])
		end
		@video.media = params[:video][:media]
		@video.user = current_user

		code = params[:video][:eligibility_code]
		@eligible = EligibilityCode.find_by_code(code)
		unless @eligible == nil
			@video.eligibility_code = @eligible
			@eligible.taken = true
			@eligible.save!
		end

		if @video.save! 
			redirect_to @video, :notice => "Successfully uploaded a video!"
		else
			render :action => "new"
		end
	end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
		@videos = Video.processed.page(params[:page])
		@all_categories = Category.all
		@ad ||= Ads.find_by_location("videos")
  end

  def show
		rand_id = rand(VideoAd.count)
		rand_record = VideoAd.processed.first(:offset => rand_id)
		@videoAd ||= rand_record
		@video = Video.find_by_id(params[:id])
		@all_categories = Category.all
		if !@video.processed?
			flash[:notice] = "Video is still Processing. Please Wait"
		end
		
  end

end

app/helpers/profile/videos_helper.rb
module Profile::VideosHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_comment.html.haml
%h3
	Leave a Reply
=form_for :comment, :url => profile_video_comments_path(@video.id), :method => :post do |comment|
	=comment.text_area :text
	%br
	=submit_tag "comment", :id => "submit"
%h3
	Comments

	-@video.comments.each do |comment|
		%div
			-unless comment.user.profilepic == nil
				%div#video-comment
					%div#video-comment-pic
						=link_to (image_tag comment.user.profilepic_url(:profile_pic) ,:style => "width:50px;height:76px"), other_user_path(comment.user.username)
					%div#video-comment-body
						%p
							%span#bold
								=link_to comment.user.username, other_user_path(comment.user.username)
							says:
						%p.time-ago
							=distance_of_time_in_words_to_now(comment.created_at)
						%br
						%p
							=comment.body
					%br{:style => "clear:both"}

app/views/videos/index.html.haml
=content_for :meta_tags do
	%meta{:name => "title", :description => "Watch Online Video Streaming | Peekbox.tv"}
	%meta{:name => "description", :description => "Watch online live streaming of user uploaded videos and free Peekbox TV shows "}
	%meta{:name => "keywords", :description => "watch videos online, watch videos for free, watch free video, tv show online, video shows, free video streaming, live video streaming, online video streaming, video tv show, video tv shows"}
%div#page-info
	%span#title
		Video Box
	%span#desc
		Viewing Users Videos Online
%br{:style => "clear:both;"}
%div#video_list
	-@videos.each do |vid|
		%div#video_each
			%div.thumbnail-wrapper
				=link_to (image_tag vid.thumbnails.first.url, :class => "thumbnails" ,:alt => "#{vid.category.title.to_s}_#{vid.title.to_s}"), video_path(vid.id)
				%div.item-title-wrapper
					%p.item-title
						= truncate(vid.title, :length => 30, :omission =>"...")
				%p.item-description
					= truncate(vid.description, :length => 30, :omission =>"...")
%div#categories
	- unless @ad == nil
		%div.ads{:style => "float:right"}
			=link_to (image_tag @ad.banner_url(:banner_ad)), @ad.url
	= render :partial => "layouts/sidebar_categories"
%br{:style=>"clear:both"}
%div
	=paginate @videos
%br{:style=>"clear:both"}

app/views/videos/show.html.haml
%div#page-info
	%span#title
		=@video.title
	%span#desc
		Viewing 
		=@video.category.title
		videos
-if @video.processed?
	%div#video-show-page
		%p
			-if @videoAd != nil 
				= video_tag(@video.media, :controls => true, :autobuffer => true, :width => "640", :id => "video-element", :ads => @videoAd.media)
			-else
				= video_tag(@video.media, :controls => true, :autobuffer => true, :width => "640", :id => "video-element")
		%p
		%div#sharethis{:style => "float:left"}
			%span.st_facebook_hcount{:displayText => "Facebook"}
			%span.st_twitter_hcount{:displayText => "Tweet"}
			%span.st_googleplus_hcount{:displayText => "google plus"}
			%span.st_sharethis_hcount{:displayText => "shareThis"}
		%div{:style => "float:left"}
			%p{:style => "margin:0px 5px 0px 5px"}
				Peeks:
				-if @video.video_bookmarks == nil
					= "0"
				-else
					= @video.video_bookmarks.count
		-unless current_user == nil
			-if current_user.is_video_bookmarked(@video)
				= button_to "", {:controller => "profile/video_bookmark", :method => "post", :video => @video.id}, {:style => "margin:0px -10px 0px 0px;padding-top:3px;", :class => "myPeekButton"}
			-else
				= button_to "", {:controller => "profile/video_bookmark", :action => "unbookmark",  :id => @video.id}, {:style => "margin:0px -10px 0px 0px;padding-top:3px", :class => "unPeekButton"}
			
		%br{:style => "clear:both"}
		-unless current_user == nil
			-if current_user.admin || current_user == @video.user
				=link_to "Edit", edit_profile_video_path(@video.id)
				=link_to "Delete", profile_video_path(@video.id), :method => :delete, :confirm => "Are you sure?"
		%br{:style => "clear:both"}
		%p
			=@video.description
		%p
			Uploaded By:
		%div#video-owner
			%div#profilepic
				-unless @video.user.profilepic_url(:profile_pic) == nil
					=image_tag @video.user.profilepic_url(:profile_pic).to_s
			%div#profile-information
				%p
					%span#bold
						Posted on:
					=@video.created_at
				%p
					%span#bold
						By:
					=@video.user.username
				%p
					%span#bold
						Posted in
					%span#category
						=@video.category.title
			%br{:style => "clear:both"}
		=render "comment"
- else
	%p
		while we process your video you can check out other Video from our list...

	= link_to "Video Gallery",videos_path