config/routes.rb
Peekbox::Application.routes.draw do
  resources :s3_uploads

	devise_for :users, :controllers => {:session => "user/session"} 

	post "zencoder-callback" => "zencoder_callback#create", :as => "zencoder_callback"

	get "profile" => "profile/profile#index"

  get "home" => "home#test_slider"


	namespace :admin do
		resources :categories, :only => [:index, :new, :create, :edit, :update] 
		resources :albums
		resources :contests do
			member do
				get "change_status"
			end
		end
		resources :eligibilities
		resources :feature, :only => [:index] do
			collection do
				get "events"
				get "special"
				get "videos"
				get "albums"
			end
		end
		resources :video_ads
		resources :ads
		resources :event_banner
		resources :banner
		resources :user do
			collection do
				get "ban"
				get "unban"
				get "ban_list"
				get "delete_user"
				get "make_admin"
				get "make_normal"
				get "admin"
			end
		end
	end

	#Users
	namespace :profile do
		resources :video_bookmark do
			collection do
				post "unbookmark"
			end
		end
		resources :picture_bookmark do
			collection do
				post "unbookmark"
			end
		end
		resources :bookmark, :only => [:index, :create, :destroy] do
			collection do
				post "unbookmark"
			end
		end
		resources :information
		resources :crop
		resources :user, :only => [:save, :update] do 
			resources :wall_post, :only => [:create, :destroy]
			collection do
				post "save"
			end
		end
		resources :users, :only => [:index] do 
			collection do
				post "search"
			end
		end
		resources :albums do
			resources :pictures do 
				collection do
					post 'multiupload'
				end
			end
		end
		resources :friends do
			collection do
				get 'search'
				get 'all'
				get 'add', :path => 'add/:id'
			end
		end
		resources :messages do
			collection do
				get "inbox"
				post "send_message"
				get "sent"
        get "trash"
				get "compose"
				post "move_to_label", :path => 'move_to_label/:id'
        get "autocomplete_user_username"
        post "delete_checked", :put

			end
		end
		resources :events
		resources :videos do
			collection do
				get "uploaded"
			end
			resources :comments
		end
	end

	#Videos
	resources :videos, :only => [:show, :index]

	# Events
	resources :events, :only => [:show, :index] do
    collection do
      get "show_to", :path => 'show_to/:id'
    end
  end

	#Albums
	resources :albums, :only => [:show, :index] do
		resources :pictures, :only => [:show, :index]
	end

	resources :category, :only => [:show], :path => "/video/category/"



	get "help" => "static#help"

	get "company" => "static#company"
	post "contact" => "static#contact"

  root :to => 'home#index'
  match ":username" => "information#show", :as => "other_user"
  match ":username/friends" => "information#friends", :as => "other_user_friends"

end

app/models/picture.rb
class Picture < ActiveRecord::Base
	belongs_to :album  
	belongs_to :user
  has_many :picture_bookmarks
	mount_uploader :image, PictureUploader
	validates_presence_of :image
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def index
		@album = Album.find_by_id(params[:album_id])
		@pictures = @album.pictures.page(params[:page])
		@user ||= @album.user
		@ad ||= Ads.find_by_location("album")
  end

  def show
		@album = Album.find_by_id(params[:album_id])
		@pictures = @album.pictures.page(params[:page]).per(1)
  end
end

app/controllers/profile/pictures_controller.rb
class Profile::PicturesController < Profile::ProfileController

  def index
			@album = current_user.albums.find(params[:album_id])
			@pictures = @album.pictures
  end

  def edit
		if current_user.admin
			@album = Album.find(params[:album_id])
		else
			@album = current_user.albums.find(params[:album_id])
		end
		@picture = Picture.find(params[:id])
  end

	def multiupload
		@album = Album.find_by_id(params[:album_id])
		if !@album.nil?
			@picture = Picture.new(params[:picture])
			@picture.user = current_user
			@picture.album = @album
			if @picture.save!
				render :nothing => true
			else
				render :nothing => true
			end
		else
			render :action => "index"
		end
	end

  def show
  end

  def create
		@album = Album.find_by_id(params[:album_id])
		if !@album.nil?
			@picture = Picture.new(params[:picture])
			@picture.user = current_user
			@picture.album = @album
			if @picture.save!
				redirect_to profile_album_pictures_path(@album), :notice => "Successfully added a Photo!"
			else
				render :action => "index"
			end
		else
			render :action => "index"
		end
  end

  def update
		@album = Album.find_by_id(params[:album_id])
		if !@album.nil?
			@picture = Picture.find(params[:id])
			@picture.user = current_user
			@picture.album = @album
			@picture.description = params[:picture][:description]
			@picture.title = params[:picture][:title]
			if @picture.save!
				redirect_to profile_album_pictures_path(@picture.album), :notice => "Successfully deleted an Picture!"	
			else
				redirect_to profile_album_pictures_path(@picture.album), :alert => "Error on deleting an Picture!"	
			end
		else
				redirect_to profile_album_pictures_path(@picture.album), :alert => "Error on fetching an album!"	
		end
  end

  def destroy
		@picture = Picture.find(params[:id])
		if current_user == @picture.user || current_user.admin
			if @picture.destroy
				redirect_to album_pictures_path(@picture.album), :notice => "Successfully deleted an Picture!"	
			else
				redirect_to profile_album_pictures_path(@picture.album), :alert => "Error on deleting an Picture!"	
			end
		end
  end

end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/profile/pictures_helper.rb
module Profile::PicturesHelper
end

app/views/pictures/index.html.haml
%div#page-info
	%span#title
		=@album.title
	%span#desc
		Viewing Album
%br{:style => "clear:both;"}
	-unless current_user == nil
		-if current_user.admin
			%div
				=link_to "Admin Delete",admin_album_path(@album.id), :method => :delete, :confirm => "Are you sure?"
				%br 
				=link_to "Admin Edit", edit_profile_album_path(@album.id)
%br{:style => "clear:both;"}
%div#albums-page
	-if @album.image?
		%div#album-page-image
			= image_tag @album.image_url(:album_cover)
	%br{:style => "clear:both"}
	-unless current_user== nil
		%p
			Uploaded By:
			%span#bold
				=link_to @user.username, other_user_path(@user.username)
		%br{:style => "clear:both;"}
	-unless @album.description == nil
		%h2
			Album Description
		%p{:style => "width:650px;"}
			=auto_link(@album.description)
		%br{:style => "clear:both;"}
-if @pictures.empty?
	%p 
		No Picture Available
-else
	%h2
		Photos
	%div#album{:style => "float:left;width:733px;padding-top:50px;"}
		=paginate @pictures
		-@pictures.each_with_index do |picture, index|
			%div#each
				%div#picture_cover.thumbnail-wrapper
					=link_to (image_tag picture.image_url(:picture_thumb).to_s), album_picture_path(picture.album, picture.id, :page => index+1) 
					%div#album_title.item-title-wrapper
						%p.item-title
							-if picture.title == nil
								="..."
							-else
								=picture.title
					%p.item-description{:style => "font-size:10px;margin-top:1px;"}
						= truncate(picture.description, :length => 30, :omission =>"...")
	
- unless @ad == nil
	%div.ads{:style => "float:right;"}
		=link_to (image_tag @ad.banner_url(:banner_ad)), @ad.url
%br{:style => "clear:both"}

app/views/pictures/show.html.haml
-@pictures.each do |pic|
	%div#page-info
		%span#title
			=pic.title
		%span#desc
	%br{:style => "clear:both"}
	%div#picture-page
		-if pic.image?
			%div#picture-page-image
				= image_tag pic.image_url(:picture_page).to_s
			%div#sharethis{:style => "float:left;text-align:right;margin:0 auto;"}
				%span.st_facebook_hcount{:displayText => "Facebook"}
				%span.st_twitter_hcount{:displayText => "Tweet"}
				%span.st_googleplus_hcount{:displayText => "google plus"}
				%span.st_sharethis_hcount{:displayText => "shareThis"}
			%div{:style => "float:left"}
				%p{:style => "margin:0px 5px 0px 5px"}
					Peeks:
					-if pic.picture_bookmarks == nil
						= "0"
					-else
						= pic.picture_bookmarks.count
			-unless current_user == nil
				-if current_user.is_picture_bookmarked(pic)
					= button_to "", {:controller => "profile/picture_bookmark", :method => "post", :picture => pic.id}, {:style => "padding-top:3px;margin-top:0px", :class => "myPeekButton"}
				-else
					= button_to "", {:controller => "profile/picture_bookmark", :action => "unbookmark",  :id => pic.id}, {:style => "padding-top:3px;margin-top:0px",:class => "unPeekButton"}
		%br{:style => "clear:both"}
		-unless current_user == nil
			-if current_user.admin || current_user == pic.user
				=link_to "Edit", edit_profile_album_picture_path(pic.album, pic)
				=link_to "Delete", profile_album_picture_path(pic.album, pic), :method => :delete, :confirm => "Are you sure?"
		%br{:style => "clear:both"}
		%p
			%p
				Description:
			%p
				=pic.description
=paginate @pictures